### ISSUE TITLE
Traefik3 docs changes.

### ISSUE THREAD

**Issue by saltydk** [saltyorg/docs#183]
~~Add explanation about how to do var overrides for instances with dashes in the name.~~

~~Short explanation is that Ansible doesn't allow dashes (while it technically works anyway we're trying to avoid problems in the future in case it becomes enforced with default vars as well) in variable names so we're renaming the instance under the hood even if the folders, docker container/hostname, and the like still contains the dash in it the variable will replace dashes with underscores.~~

**Comment by owine** [comment]
Also needed

- [ ] Authelia LDAP
- [ ] DB multi instance and notes on migration

**Comment by owine** [comment]
> 

https://github.com/saltyorg/docs/commit/41b63fc8df5b35fd497a7c791ab8d81dcb9950a4

**Comment by owine** [comment]
Explain media_server, download_clients and download_indexers roles and how to use them to change the apps installed by Saltbox, Mediabox and Feederbox tags.

#178

**Comment by owine** [comment]
```
traefik_tailscale_enabled: true # global toggle for tailscale entrypoint creation
traefik_traefik_tailscale_enabled: true # if you want dash to use tailscale
netdata_traefik_tailscale_enabled: true # role toggle
traefik_tailscale_bind_ip: "" # Set to override the WANIP port binding when server is not connected directly to the Internet.
traefik_tailscale_bind_ipv6: "" # Same but IPv6
```

#184

**Comment by saltydk** [comment]
Roles being moved from Sandbox to Saltbox
* autobrr
* dozzle
* unpackerr
* whisparr

**Comment by saltydk** [comment]
add warning about backup.yml changes for users of backup2.

**Comment by owine** [comment]
I think we need a page dedicated to this migration/upgrade

**Comment by saltydk** [comment]
document restore_tar functionality to restore a single app

**Comment by saltydk** [comment]
document qbittorrent host install

**Comment by saltydk** [comment]
document backup_rclone_env

**Comment by saltydk** [comment]
qbittorrent will be the default torrent client

**Comment by saltydk** [comment]
document the legacy volume toggle

```yaml
docker_legacy_volume: false
```

**Comment by saltydk** [comment]
document mounts_override
```yaml
mounts_override: true
```

**Comment by saltydk** [comment]
document these toggles
```yaml
skip_dns: false
role_dns_enabled: "{{ lookup('vars', role_name + '_dns_enabled', default=true) }}"
```

**Comment by saltydk** [comment]
document the traefik middleware var changes.

```yaml
speedtest_traefik_sso_middleware: ""
speedtest_traefik_middleware_default: "{{ traefik_default_middleware }}"
speedtest_traefik_middleware_custom: ""
```
instead of 
```yaml
speedtest_traefik_middleware: "{{ traefik_default_middleware }}"
```
since inventory edits that try editing the old middleware var won't do anything anymore.

**Comment by saltydk** [comment]
document traefik API whitelisting change.

**Comment by saltydk** [comment]
document how to migrate databases from legacy installs to the new per app instance database format.

**Comment by saltydk** [comment]
add templates for external services to the advanced section, such as this 
```yaml
http:
  routers:
    ansible-http:
      entryPoints:
        - "web"
      rule: "Host(`ansible.saltbox.dev`)"
      middlewares:
        - globalHeaders
        - redirect-to-https@docker
        - gzip@docker
      service: "ansible"
    ansible:
      entryPoints:
        - "websecure"
      rule: "Host(`ansible.saltbox.dev`)"
      middlewares:
        - globalHeaders
        - secureHeaders
        - gzip@docker
      service: "ansible"
      tls:
        options: securetls@file
        certResolver: google
        domains:
          - main: "saltbox.dev"
            sans:
              - "*.saltbox.dev"
  services:
    ansible:
      loadBalancer:
        servers:
        - url: "http://172.19.0.1:8000"
```

**Comment by saltydk** [comment]
document the backup role template change in the config

**Comment by saltydk** [comment]
add set-backup/unset-backup crontab toggle explanation to the Traefik 3.0 upgrade explainer since it might confuse longtime users.
backup2 has set-backup2/unset-backup2 to toggle the crontab entry.

**Comment by saltydk** [comment]
maybe we should mention the rutorrent image change which means no more autodl?

**Comment by saltydk** [comment]
document the new way of toggling rclone remotes:

old way
```yaml
---
downloads: /mnt/unionfs/downloads
transcodes: /mnt/local/transcodes
rclone:
  version: latest
  remote: 
shell: bash
authelia:
  master: yes
  subdomain: login
```
new way
```yaml
---
authelia:
  master: yes
  subdomain: login
downloads: /mnt/unionfs/downloads
rclone:
  enabled: false <-- this
  remotes:
    - remote: google
      template: google
      vfs_cache:
        enabled: false
        max_age: 504h
        size: 50G
  version: latest
shell: bash
transcodes: /mnt/local/transcodes
```
Change was done to avoid having to redo the whole list structure in order to toggle deploying rclone remotes. The role will remove previously deployed Saltbox rclone services when disabled.
