### ISSUE TITLE
Document Tailscale feature

### ISSUE THREAD

**Issue by owine** [saltyorg/docs#184]
```yaml
traefik_tailscale_enabled: true # global toggle for tailscale entrypoint creation
traefik_traefik_tailscale_enabled: true # if you want dash to use tailscale
netdata_traefik_tailscale_enabled: true # role toggle
```
