### ISSUE TITLE
Add API endpoint examples to advanced/your-own-containers.md

### ISSUE THREAD

**Issue by RaneyDazed** [saltyorg/docs#244]
I was looking for an example of adding some endpoints to immich, and looked at prowlarr as an example. ie:
```yaml
                "traefik.enable": "true",
                "traefik.http.routers.prowlarr-api-http.entrypoints": "web",
                "traefik.http.routers.prowlarr-api-http.middlewares": "globalHeaders@file,redirect-to-https,cloudflarewarp",
                "traefik.http.routers.prowlarr-api-http.priority": "30",
# This one for example -->
                "traefik.http.routers.prowlarr-api-http.rule": "(Host(`prowlarr.domain.tld`)) && (PathRegexp(`/[0-9]+/api`) || PathRegexp(`/[0-9]+/download`) || PathPrefix(`/api`) || PathPrefix(`/ping`))",
                "traefik.http.routers.prowlarr-api-http.service": "prowlarr",
                "traefik.http.routers.prowlarr-api.entrypoints": "websecure",
                "traefik.http.routers.prowlarr-api.middlewares": "globalHeaders@file,secureHeaders@file,cloudflarewarp",
                "traefik.http.routers.prowlarr-api.priority": "30",
                "traefik.http.routers.prowlarr-api.rule": "(Host(`prowlarr.domain.tld`)) && (PathRegexp(`/[0-9]+/api`) || PathRegexp(`/[0-9]+/download`) || PathPrefix(`/api`) || PathPrefix(`/ping`))",
                "traefik.http.routers.prowlarr-api.service": "prowlarr",
                "traefik.http.routers.prowlarr-api.tls.certresolver": "cfdns",
                "traefik.http.routers.prowlarr-api.tls.options": "securetls@file",
                "traefik.http.routers.prowlarr-http.entrypoints": "web",
                "traefik.http.routers.prowlarr-http.middlewares": "globalHeaders@file,redirect-to-https,cloudflarewarp,authelia",
                "traefik.http.routers.prowlarr-http.priority": "20",
                "traefik.http.routers.prowlarr-http.rule": "Host(`prowlarr.domain.tld`)",
                "traefik.http.routers.prowlarr-http.service": "prowlarr-http",
                "traefik.http.routers.prowlarr.entrypoints": "websecure",
                "traefik.http.routers.prowlarr.middlewares": "globalHeaders@file,secureHeaders@file,cloudflarewarp,authelia",
                "traefik.http.routers.prowlarr.priority": "20",
                "traefik.http.routers.prowlarr.rule": "Host(`prowlarr.domain.tld`)",
                "traefik.http.routers.prowlarr.service": "prowlarr",
                "traefik.http.routers.prowlarr.tls.certresolver": "cfdns",
                "traefik.http.routers.prowlarr.tls.options": "securetls@file",
                "traefik.http.services.prowlarr-http.loadbalancer.server.port": "9696",
                "traefik.http.services.prowlarr.loadbalancer.server.port": "9696"
```
